package menion.android.whereyougo.maps.mapsforge.mapgenerator;

public enum MapGeneratorInternal {
    BLANK,
    DATABASE_RENDERER,
    OPENSTREETMAP,
    OPENSTREETMAP_DE,
    OPENCYCLEMAP_CYCLE,
    OPENCYCLEMAP_TRANSPORT,
    OPENMAPSURFER_ROADS,
    MAPQUEST,
    MAPQUEST_AERIAL,
    THUNDERFOREST_OPENCYCLEMAP,
    THUNDERFOREST_TRANSPORT,
    THUNDERFOREST_LANDSCAPE,
    THUNDERFOREST_OUTDOORS,
    ESRI_WORLD_STREET_MAP,
    ESRI_WORLD_IMAGERY
}
