// 
// Decompiled by Procyon v0.5.34
// 

package menion.android.whereyougo.maps.mapsforge.mapgenerator;

public enum MapGeneratorInternal
{
    BLANK, 
    DATABASE_RENDERER, 
    ESRI_WORLD_IMAGERY, 
    ESRI_WORLD_STREET_MAP, 
    MAPQUEST, 
    MAPQUEST_AERIAL, 
    OPENCYCLEMAP_CYCLE, 
    OPENCYCLEMAP_TRANSPORT, 
    OPENMAPSURFER_ROADS, 
    OPENSTREETMAP, 
    OPENSTREETMAP_DE, 
    THUNDERFOREST_LANDSCAPE, 
    THUNDERFOREST_OPENCYCLEMAP, 
    THUNDERFOREST_OUTDOORS, 
    THUNDERFOREST_TRANSPORT;
}
